name: Automatic Web Deploy
on: [push, pull_request]
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Publish Project
      run: dotnet publish ./JustMyTools/JustMyTools.csproj --configuration Release --output ./output
    - name: Update Base-Tag
      run: sed -i 's/<base href="\/"\/>/<base href="\/JustMyTools\/"\/>/g' ./output/wwwroot/index.html
    - name: Disable Jekyll
      run: touch ./output/wwwroot/.nojekyll
    - name: Deploy To GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: website
        FOLDER: output/wwwroot
        SINGLE_COMMIT: true
