name: Quick Publish & Deploy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Publish Project
      run: dotnet publish ./CommonToolsOnline/CommonToolsOnline.csproj --configuration Release --output ./CommonToolsOnline/Output
    - name: Delete Debug Index
      run: rm ./CommonToolsOnline/Output/wwwroot/index.html
    - name: Add Release Index
      run: mv ./CommonToolsOnline/Output/wwwroot/index-release.html ./CommonToolsOnline/Output/wwwroot/index.html
    - name: Deploy To GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: website
        FOLDER: CommonToolsOnline/Output/wwwroot
        SINGLE_COMMIT: true
